### ISSUE TITLE
How do you Implement this?

### ISSUE THREAD

**Issue by xandorxicay** [nicolasartman/web-inspector-dark-theme#1]
I tried adding the custom.css on preference-advance for safari but It didn't work.

**Comment by thiago-om** [comment]
I'd love to know how to do this too, I've searched everywhere and the old method of editing safari's css file is no longer applicable as the file does not seem to exist on Safari 8

**Comment by tlattimore** [comment]
I would also like to know how to do this. I suspect that this feature is something that has been disabled in Safari 8.

**Comment by ylluminarious** [comment]
@nicolasartman I have the same issue as mentioned above. Is this project simply dead and no longer usable or is there something that I'm missing in order to activate this theme?

**Comment by nicolasartman** [comment]
Yea, safari has completely changed the devtools interface since then and none of the CSS classes match any more.

It was far too much work to keep up with chrome and safari's undocumented changes to their core stylesheets, so yes, this particular style isn't usable anymore. I'll add a deprecation note to the readme.

Chrome now has an experimental devtools theme system, so if you're using chrome and want a similar (much better, in fact) theme to this one you can check out https://github.com/nicolasartman/zero-base-themes

**Comment by ylluminarious** [comment]
@nicolasartman Ok, well thanks for the update. Unfortunately for me, Safari is my preferred browser, so I guess I'll just have to deal with their ugly theme or perhaps make a suggestion to Apple for them to make different themes for the inspector. But yeah, thanks for the info and also for the link to that other project.

**Comment by nicolasartman** [comment]
sure thing. best of luck!
